name: 'Get the blob'
description: 'Fetch content from blob and write to a file'
inputs:
  storage_account_name:
    required: true
  account_access_key:
    required: true
  container_name:
    required: true
  blob_prefix:
    required: true
  output_file:
    description: File path
    required: true
outputs:
  success:
    description: 'Content from blob'
runs:
  using: 'node12'
  main: 'index.js'
