name: 'Get the blob'
description: 'Get the blob and write to a file'
inputs:
  storage_account_name:
    required: true
  account_access_key:
    required: true
  container_name:
    description: 'Name of blob storage container'
    required: true
  blob_prefix:
    description: 'Beginning of name of blob'
    required: true
  output_file:
    required: true
outputs:
  success:
    description: 'Content from blob'
runs:
  using: 'node12'
  main: 'index.js'
