name: Download file from azure, custom js
on: workflow_dispatch
jobs: 
  fetch_blob:
     name: Download content from azure and save to json file
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v2
         with:
            node-version: '12'
       - uses: ./blob-fetch
         with:
           storage_account_name: ${{ secrets.SN_STORAGE_ACCOUNT_NAME }}
           account_access_key: ${{ secrets.SN_ACCOUNT_ACCESS_KEY }}
           container_name: ${{ secrets.SN_CONTAINER_NAME }}
           blob_prefix: ${{ secrets.SN_BLOB_PREFIX }}
           output_file: 'blob-fetch/results.json'
       - name: Commit edited json file
         run: |
          git status	
          git config --local user.name  ${{ github.actor }}	
          git add blob-fetch/results.json	
          git commit -m "Update json file with blob content"	
       - name: Push changes 
         uses: ad-m/github-push-action@master	
         with:	
          github_token: ${{ secrets.TOKEN }}	
          force: true  

