name: Download file from azure
on: [workflow_dispatch, push]
jobs: 
  fetch_blob:
     name: Download file from azure
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v1
       - uses: ./blob-fetch
         id: download_blob
         with:
           action: download
           storage_account_name: sleepscience
           account_access_key: ${{ secrets.ACCOUNT_ACCESS_KEY }}
           container_name: states
           blob_prefix: us
           output_file: results.json
       - name:  results
         run: echo ${{steps.download_blob.outputs}}
          
