name: Download file from azure 2
on: workflow_dispatch
jobs: 
  fetch_blob:
     name: Download from azure, no custom action
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v1
       - uses: actions/setup-node@v2
         with:
            node-version: '12'
       - run: npm install
       - name: Copy files
         uses: ulaval/azure-blob-copy-action@v1
         with:
          action: download
          connection_string: ${{ secrets.CONNECTION_STRING }}
          container_name: states
          local_directory: /
       - name: Commit file
         run: |	
          git status
          git config --local user.name  ${{ github.actor }}	
          git add us_map_data
          git commit -m "Save blob to repo"	
       - name: Push changes 
         uses: ad-m/github-push-action@master	
         with:	
          github_token: ${{ secrets.TOKEN }}	
          force: true  
