name: Download file from azure
on: [workflow_dispatch, push]
jobs: 
  fetch_blob:
     name: Download file from azure
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v1
       - uses: actions/setup-node@v2
         with:
            node-version: '12'
       - run: npm install
       - uses: ./blob-fetch
         id: download_blob
         with:
           storage_account_name: sleepscience
           account_access_key: ${{ secrets.ACCOUNT_ACCESS_KEY }}
           container_name: states
           blob_prefix: us
           output_file: '../../results.json'
       - uses: DamianReeves/write-file-action@v1.0
         with:
          path: '../../results.json'
          contents: "Hello World!"
          write-mode: overwrite

